stages:
  - install
  - tests
  - build
  - publish

variables:
  DOMAIN: esciencedatafactory.com
  SCOPE: semaphora

npm_install:
  stage: install
  image: node:latest
  script:
    - npm install
  artifacts:
    name: node_modules
    paths:
      - node_modules
    expire_in: 2 weeks

.npm_build:
  stage: build
  image: node:latest
  needs:
    - job: npm_install
      optional: false
  script:
    - npm run build
  artifacts:
    name: compiled_code
    paths:
      - dist
    expire_in: 2 weeks

.tests:
  stage: tests
  image: node:latest
  when: manual
  needs:
    - job: npm_install
      optional: false
  script:
    - npm test

publish_npm_package:
  stage: publish
  image: node:latest
  when: manual
  needs:
    - job: npm_install
      optional: false
  before_script:
    - npm config set @${SCOPE}:registry=https://gitlab.${DOMAIN}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
    - npm config set //gitlab.${DOMAIN}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}
  script:
    - npm install -g typescript
    - npm publish

